version: "3.8"

services:
  postgres:
    container_name: explore
    image: postgres
    ports:
      - 3334:5432
    environment:
      POSTGRES_USER: explore
      POSTGRES_PASSWORD: explore
      POSTGRES_DB: explore_db
